<?php 
 return array (
  'COOKIE_EXPIRE' => '3600',
  'COOKIE_DOMAIN' => '',
  'COOKIE_PATH' => '/',
  'SESSION_PREFIX' => '',
  'SESSION_OPTIONS' => 
  array (
    'domain' => '',
  ),
  'SHOW_ERROR_MSG' => '1',
  'ERROR_MESSAGE' => '您浏览的页面暂时发生了错误！请稍后再试～',
  'ERROR_PAGE' => '',
  'URL_CASE_INSENSITIVE' => false,
  'URL_MODEL' => 0,
  'URL_PATHINFO_DEPR' => '/',
  'URL_HTML_SUFFIX' => '.html',
  'TOKEN_ON' => true,
  'TOKEN_NAME' => '__hash__',
  'TOKEN_TYPE' => 'md5',
  'PAGE_LISTROWS' => '20',
  'VAR_PAGE' => 'page',
  'DEFAULT_GROUP' => 'Contents',
  'DEFAULT_TIMEZONE' => 'PRC',
  'DEFAULT_AJAX_RETURN' => 'JSON',
  'DEFAULT_FILTER' => 'htmlspecialchars',
  'DEFAULT_LANG' => 'zh-cn',
  'DATA_CACHE_TYPE' => 'File',
  'SESSION_AUTO_START' => '0',
);